import { describe, expect, it } from 'vitest';
import { calculateAdaptationMetrics, createAdaptationService, type AdaptationRecord, type AdaptationRepository, type ExecutionSession } from '../src/modules/adaptation/adaptationService.js';
const user = { userId: 'alice', token: 't' } as any;
function repo(sessions: ExecutionSession[]): AdaptationRepository { let row: AdaptationRecord | null = null; return { async get() { return row; }, async save(_u, input) { row = { id: 'r', user: 'alice', ...input } as AdaptationRecord; return row; }, async listSessions() { return sessions; } }; }
describe('adaptation', () => {
  it('ignores incomplete/cancelled sessions and bounds outliers', () => { const metrics = calculateAdaptationMetrics([{ status: 'finished', plannedMinutes: 50, actualMinutes: 60, finishedAt: '2026-07-19T10:00:00Z', category: 'deep' }, { status: 'paused', plannedMinutes: 50, actualMinutes: 500 }, { status: 'finished', plannedMinutes: 0, actualMinutes: 20 }, { status: 'finished', plannedMinutes: 10, actualMinutes: 1000, finishedAt: 'bad' }]); expect(metrics.sampleSize).toBe(1); expect(metrics.byCategory.deep.multiplier).toBe(1.2); });
  it('requires consent and explicit acceptance', async () => { const service = createAdaptationService(repo([{ status: 'finished', plannedMinutes: 50, actualMinutes: 70, finishedAt: '2026-07-19T10:00:00Z', category: 'deep' }, { status: 'finished', plannedMinutes: 50, actualMinutes: 70, finishedAt: '2026-07-19T10:05:00Z', category: 'deep' }, { status: 'finished', plannedMinutes: 50, actualMinutes: 70, finishedAt: '2026-07-19T10:10:00Z', category: 'deep' }])); expect((await service.get(user)).suggestions).toHaveLength(0); await service.setConsent(user, true); const result = await service.get(user); expect(result.suggestions.length).toBeGreaterThan(0); expect((await service.accept(user, result.suggestions[0].id)).status).toBe('accepted'); });
  it('requires consent and clears learned profile on reset', async () => { const service = createAdaptationService(repo([])); await service.setConsent(user, true); await service.reset(user); expect((await service.get(user)).consent).toBe(false); await expect(service.accept(user, 'missing')).rejects.toThrow(); });
});
