import { describe, expect, it, vi } from 'vitest';
import { createGoalService } from '../src/modules/goals/goalService.js';
import type { GoalGraphRepository } from '../src/repositories/goalGraphRepository.js';

const user = { userId: 'alice', email: 'a@test' };
function setup() {
  const rows: Record<string, any[]> = { goals: [], projects: [], ideas: [{ id: 'i1', user: 'alice', text: 'Епізод про синдром самозванця', summary: 'Тема', status: 'backlog' }], edges: [] }; let seq = 0;
  const make = (name: string) => ({ list: vi.fn(async (u: any) => rows[name].filter((r) => r.user === u.userId)), get: vi.fn(async (u: any, id: string) => rows[name].find((r) => r.id === id && r.user === u.userId) ?? null), create: vi.fn(async (u: any, input: any) => { const r = { id: `${name}-${++seq}`, user: u.userId, ...input }; rows[name].push(r); return r; }), update: vi.fn(async (u: any, id: string, input: any) => { const r = rows[name].find((x) => x.id === id && x.user === u.userId); Object.assign(r, input); return { ...r }; }), delete: vi.fn(async (u: any, id: string) => { const i = rows[name].findIndex((x) => x.id === id && x.user === u.userId); if (i >= 0) rows[name].splice(i, 1); }) });
  const repository = { goals: make('goals'), projects: make('projects'), ideas: make('ideas'), edges: make('edges') } as unknown as GoalGraphRepository;
  const changes: any[] = []; const changeSetRepository: any = { list: vi.fn(async (u: any) => changes.filter((x) => x.user === u.userId)), get: vi.fn(async (u: any, id: string) => changes.find((x) => x.id === id && x.user === u.userId) ?? null), create: vi.fn(async (u: any, input: any) => { const c = { id: `change-${++seq}`, user: u.userId, ...input }; changes.push(c); return c; }), update: vi.fn(async (_u: any, id: string, input: any) => { const c = changes.find((x) => x.id === id); Object.assign(c, input); return c; }), transition: vi.fn(async (_u: any, id: string, _from: string, to: string, input: any) => { const c = changes.find((x) => x.id === id); Object.assign(c, input, { status: to }); return c; }) };
  const tasks: any[] = []; const taskRepository: any = { create: vi.fn(async (u: any, input: any) => { const t = { id: `task-${++seq}`, user: u.userId, ...input }; tasks.push(t); return t; }), delete: vi.fn(async (_u: any, id: string) => { const i = tasks.findIndex((t) => t.id === id); if (i >= 0) tasks.splice(i, 1); }) };
  return { rows, changes, tasks, service: createGoalService({ repository, changeSetRepository, taskRepository }) };
}

describe('goals, projects, ideas and Oracle graph domain', () => {
  it('limits free users to one active goal with paywall-shaped error', async () => { const s = setup(); await s.service.goals.create(user, { title: 'Мета' }); await expect(s.service.goals.create(user, { title: 'Друга' })).rejects.toMatchObject({ code: 'ENTITLEMENT_REQUIRED' }); });
  it('keeps AI edges proposed and supports cycles/many-to-many without deleting nodes', async () => { const s = setup(); const a = await s.service.graph.create(user, { fromType: 'idea', fromId: 'i1', toType: 'goal', toId: 'g1', actor: 'ai' }); expect(a.status).toBe('proposed'); await expect(s.service.graph.create(user, { fromType: 'idea', fromId: 'i1', toType: 'goal', toId: 'g1', actor: 'ai', status: 'confirmed' })).rejects.toMatchObject({ code: 'INVALID_GOAL' }); await s.service.graph.delete(user, a.id); expect(s.rows.ideas).toHaveLength(1); });
  it('requires explicit confirmation for idempotent idea conversion and supports Undo', async () => { const s = setup(); const preview = await s.service.conversion.preview(user, 'i1', {}); expect(preview.requiresConfirmation).toBe(true); await expect(s.service.conversion.apply(user, 'i1', { confirm: false })).rejects.toMatchObject({ code: 'INVALID_GOAL' }); const applied = await s.service.conversion.apply(user, 'i1', { confirm: true, idempotencyKey: 'convert-123456' }); expect(applied.project).toBeTruthy(); expect((await s.service.ideas.get(user, 'i1')).status).toBe('converted'); const again = await s.service.conversion.apply(user, 'i1', { confirm: true, idempotencyKey: 'convert-123456' }); expect(again.changeSet.id).toBe(applied.changeSet.id); await s.service.conversion.undo(user, applied.changeSet.id); expect((await s.service.ideas.get(user, 'i1')).status).toBe('backlog'); });
  it('does not expose another user records as valid IDs', async () => { const s = setup(); s.rows.goals.push({ id: 'other', user: 'bob', title: 'секрет' }); await expect(s.service.goals.get(user, 'other')).rejects.toMatchObject({ code: 'NOT_FOUND' }); });
});
