import { ArrowRight, Check, Folder, Lightbulb, Sparkle } from "@phosphor-icons/react";
import { AppFrame } from "../../components/AppFrame";
import { Button } from "../../components/Button";
import { InlineInsight } from "../../components/InlineInsight";
import { LinearProgress } from "../../components/Progress";
import { TaskCard } from "../../components/TaskCard";
import { DEMO_GOAL, DEMO_IDEAS, DEMO_PROJECTS, DEMO_TASKS } from "../../data/demoData";

export function IdeaProjectScreens({ screenId, onNavigate = () => {} }) {
  if (screenId === "project-detail") return <AppFrame title="Пілотний епізод" eyebrow="Проєкт" onBack={() => onNavigate("inbox-default")} activeRoute="inbox-default" onNavigate={onNavigate}><section className="project-hero"><Folder size={28} weight="duotone" /><span><h1>{DEMO_PROJECTS[0].title}</h1><p>Результат: записаний та змонтований пілот</p></span></section><LinearProgress value={38} label="Прогрес проєкту" /><InlineInsight title="Зв'язок із метою">Цей проєкт напряму веде до запуску першого сезону подкасту.</InlineInsight><div className="detail-list"><h2>Задачі</h2>{DEMO_TASKS.slice(0,2).map((task) => <TaskCard key={task.id} task={task} />)}</div></AppFrame>;
  if (screenId === "idea-decomposition") return <AppFrame title="Майбутній проєкт" eyebrow="AI-декомпозиція" onBack={() => onNavigate("idea-detail")} activeRoute="inbox-default" onNavigate={onNavigate}><InlineInsight>Я пропоную створити проєкт і три конкретні кроки. Нічого не потрапить у календар до підтвердження.</InlineInsight><section className="decomposition"><div className="decomposition__project"><Folder size={22} /><span><strong>Епізод про синдром самозванця</strong><small>Новий проєкт · пов'язаний із головною метою</small></span></div>{["Зібрати 5 ключових тез","Знайти релевантного гостя","Підготувати чернетку структури"].map((item,index) => <div className="decomposition__task" key={item}><span>{index+1}</span><strong>{item}</strong><small>{[25,20,45][index]} хв</small></div>)}</section><Button onClick={() => onNavigate("project-detail")}>Створити проєкт і запланувати</Button></AppFrame>;
  const idea = DEMO_IDEAS[0];
  return <AppFrame title="Ідея" eyebrow="Backlog" onBack={() => onNavigate("inbox-default")} activeRoute="inbox-default" onNavigate={onNavigate}><section className="idea-hero"><span><Lightbulb size={28} weight="duotone" /></span><h1>{idea.title}</h1><p>AI-підсумок: перспективний тематичний епізод, який підсилює позиціонування сезону.</p></section><div className="alignment-card"><div><Sparkle size={20} /><span><strong>86% до головної мети</strong><small>{DEMO_GOAL.title}</small></span></div><ArrowRight size={19} /></div><div className="related-nodes"><h2>Пов'язані вузли</h2><span><Folder size={17} />Пілотний епізод</span><span><Check size={17} />Дослідити формат інтерв'ю</span></div><div className="detail-actions"><Button onClick={() => onNavigate("idea-decomposition")}>Розбити на задачі</Button><Button variant="secondary">Залишити в backlog</Button></div></AppFrame>;
}
