import { useEffect, useState } from "react";
import { Bell, Brain, Clock, Crown, Lightning, Moon, SlidersHorizontal, Sparkle, Target } from "@phosphor-icons/react";
import { AppFrame } from "../../components/AppFrame";
import { Button } from "../../components/Button";
import { InlineInsight } from "../../components/InlineInsight";
import { StateView } from "../../components/StateView";
import { UndoSnackbar } from "../../components/UndoSnackbar";
import { DEMO_USER } from "../../data/demoData";
import { IntegrationRow } from "./IntegrationRows";
import { TimePicker } from "../../components/TimePicker";

const menu = [
  ["settings-work", Clock, "Робочий ритм", "Пн–Пт · 09:00–18:00"],
  ["settings-energy", Lightning, "Енергія та фокус", "Пік 09:30–12:30 · блок 50 хв"],
  ["settings-notifications", Bell, "Сповіщення", "Telegram · тихі години 21:00–08:00"],
  ["settings-adaptation", Brain, "AI-адаптація", "1 нове спостереження"],
  ["goals-default", Target, "Мої цілі", "1 активна мета"],
  ["settings-pro", Crown, "Lifetime Pro", "Без підписки"],
];

function SettingsForm({ screenId, notificationPreferences, onNotificationChange }) {
  const [workStart, setWorkStart] = useState("09:00");
  const [workEnd, setWorkEnd] = useState("18:00");
  const [energyPeak, setEnergyPeak] = useState("morning");
  const [focusBlock, setFocusBlock] = useState("50");
  const [breakMinutes, setBreakMinutes] = useState("10");
  const [dailyLimit, setDailyLimit] = useState("6");
  if (screenId === "settings-work") return <div className="form-stack"><label>Робочі дні<select defaultValue="weekdays"><option value="weekdays">Понеділок–п'ятниця</option><option value="daily">Щодня</option><option value="custom">Власні дні</option></select></label><div className="form-grid"><TimePicker label="Початок" value={workStart} onChange={setWorkStart} title="Вибери час початку" /><TimePicker label="Завершення" value={workEnd} onChange={setWorkEnd} title="Вибери час завершення" /></div><label className="switch-row"><span>Планувати у вихідні</span><input type="checkbox" /></label></div>;
  if (screenId === "settings-energy") return <div className="form-stack"><label htmlFor="settings-energy-peak">Пік енергії<select id="settings-energy-peak" value={energyPeak} onChange={(event) => setEnergyPeak(event.target.value)}><option value="morning">Ранок · 09:30–12:30</option><option value="day">День · 12:30–15:30</option><option value="evening">Вечір · 17:00–20:00</option></select></label><div className="form-grid"><label htmlFor="settings-focus-block">Фокус-блок<select id="settings-focus-block" value={focusBlock} onChange={(event) => setFocusBlock(event.target.value)}>{[25, 50, 60, 90].map((value) => <option key={value} value={value}>{value} хв</option>)}</select></label><label htmlFor="settings-break">Перерва<select id="settings-break" value={breakMinutes} onChange={(event) => setBreakMinutes(event.target.value)}>{[5, 10, 15, 20].map((value) => <option key={value} value={value}>{value} хв</option>)}</select></label></div><label htmlFor="settings-daily-limit">Денний ліміт<select id="settings-daily-limit" value={dailyLimit} onChange={(event) => setDailyLimit(event.target.value)}>{[3, 4, 5, 6, 7, 8].map((value) => <option key={value} value={value}>{value} год</option>)}</select></label><InlineInsight>Вектор помітив, що 50-хвилинні блоки завершуються найчастіше.</InlineInsight></div>;
  return <div className="form-stack">
    <label>Часовий пояс<select aria-label="Часовий пояс" value={notificationPreferences.timezone} onChange={(event) => onNotificationChange({ timezone: event.target.value })}><option value="Europe/Warsaw">Europe/Warsaw</option><option value="Europe/Kyiv">Europe/Kyiv</option><option value="UTC">UTC</option></select></label>
    <div className="form-grid"><TimePicker label="Тихі години від" value={notificationPreferences.quietStart} onChange={(value) => onNotificationChange({ quietStart: value })} title="Вибери початок тихих годин" /><TimePicker label="Тихі години до" value={notificationPreferences.quietEnd} onChange={(value) => onNotificationChange({ quietEnd: value })} title="Вибери завершення тихих годин" /></div>
    <label className="switch-row"><span><Bell size={19} />Ранковий план</span><input type="checkbox" checked={notificationPreferences.morningPlanEnabled} onChange={(event) => onNotificationChange({ morningPlanEnabled: event.target.checked })} /></label>
    <label className="switch-row"><span><Bell size={19} />Нагадування про задачі</span><input type="checkbox" checked={notificationPreferences.remindersEnabled} onChange={(event) => onNotificationChange({ remindersEnabled: event.target.checked })} /></label>
    <label className="switch-row"><span><Moon size={19} />Вечірній підсумок</span><input type="checkbox" checked={notificationPreferences.eveningReviewEnabled} onChange={(event) => onNotificationChange({ eveningReviewEnabled: event.target.checked })} /></label>
    <p className="form-help">У тихі години Вектор не надсилає звичайні нагадування. Важливі системні повідомлення залишаються доступними.</p>
  </div>;
}

export function SettingsScreens({ screenId = "settings-home", onNavigate = () => {}, apiClient }) {
  const [saved, setSaved] = useState(false);
  const [telegramStatus, setTelegramStatus] = useState(null);
  const [adaptation, setAdaptation] = useState({ consent: false, suggestions: [] });
  const [notificationPreferences, setNotificationPreferences] = useState({ timezone: "Europe/Warsaw", quietStart: "21:00", quietEnd: "08:00", remindersEnabled: true, morningPlanEnabled: true, eveningReviewEnabled: true });
  const updateNotificationPreferences = (patch) => setNotificationPreferences((current) => ({ ...current, ...patch }));
  useEffect(() => { if (screenId !== "settings-notifications" || !apiClient) return; let active = true; apiClient.request("/api/v1/settings/notifications").then((result) => active && setNotificationPreferences((current) => ({ ...current, ...result }))).catch(() => {}); return () => { active = false; }; }, [screenId, apiClient]);
  const saveSettings = async () => { if (screenId === "settings-notifications" && apiClient) { try { const savedPreferences = await apiClient.request("/api/v1/settings/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(notificationPreferences) }); setNotificationPreferences((current) => ({ ...current, ...savedPreferences })); } catch { /* Keep the local draft visible and allow retry. */ } } setSaved(true); };
  useEffect(() => { if (screenId !== "settings-telegram" || !apiClient) return; let active = true; apiClient.request("/api/v1/integrations/telegram/status").then((result) => active && setTelegramStatus(result)).catch(() => active && setTelegramStatus({ status: "error" })); return () => { active = false; }; }, [screenId, apiClient]);
  useEffect(() => { if (screenId !== "settings-adaptation" || !apiClient) return; let active = true; apiClient.request("/api/v1/adaptation").then((result) => active && setAdaptation(result)).catch(() => {}); return () => { active = false; }; }, [screenId, apiClient]);
  if (["settings-work","settings-energy","settings-notifications"].includes(screenId)) return <AppFrame title={screenId === "settings-work" ? "Робочий ритм" : screenId === "settings-energy" ? "Енергія та фокус" : "Сповіщення"} onBack={() => onNavigate("settings-home")} noNav footer={<Button onClick={saveSettings}>Зберегти</Button>}><SettingsForm screenId={screenId} notificationPreferences={notificationPreferences} onNotificationChange={updateNotificationPreferences} />{saved ? <UndoSnackbar message="Налаштування збережено" onUndo={() => setSaved(false)} /> : null}</AppFrame>;
  if (screenId === "settings-telegram") { const connected = apiClient ? telegramStatus?.status === "connected" : true; const disconnect = async () => { if (apiClient) await apiClient.request("/api/v1/integrations/telegram", { method: "DELETE" }); setTelegramStatus({ status: "disconnected" }); }; return <AppFrame title="Telegram" onBack={() => onNavigate("settings-home")} noNav footer={connected ? <Button variant="danger" onClick={disconnect}>Відключити Telegram</Button> : <Button onClick={() => onNavigate("telegram-connect")}>Підключити Telegram</Button>}><IntegrationRow type="telegram" status={connected ? "connected" : telegramStatus?.status === "error" ? "error" : "disabled"} /><section className="integration-detail"><h1>{connected ? "Telegram підключено" : "Telegram ще не підключено"}</h1><p>Голосові думки, ранковий план, нагадування та результати перепланування приходять у бот.</p>{connected ? <><label className="switch-row"><span>Приймати голосові</span><input type="checkbox" defaultChecked /></label><label className="switch-row"><span>Кнопка Undo у повідомленнях</span><input type="checkbox" defaultChecked /></label></> : <p>Створи одноразове посилання, щоб безпечно прив'язати чат.</p>}</section></AppFrame>; }
  if (screenId === "settings-calendar") return <AppFrame title="Google Calendar" onBack={() => onNavigate("settings-home")} noNav footer={<Button variant="secondary">Синхронізувати зараз</Button>}><IntegrationRow type="calendar" status="syncing" /><section className="integration-detail"><h1>Двостороння синхронізація</h1><p>Події Google блокують час. Задачі Вектора з'являються як окремі календарні блоки.</p><div className="sync-stats"><span><strong>18</strong>подій прочитано</span><span><strong>4</strong>AI-блоки створено</span></div></section></AppFrame>;
  if (screenId === "settings-adaptation") {
    const proposal = adaptation.suggestions[0];
    const decide = async (action) => { if (apiClient && proposal) { await apiClient.request(`/api/v1/adaptation/suggestions/${proposal.id}/${action}`, { method: "POST" }); setAdaptation((current) => ({ ...current, suggestions: current.suggestions.slice(1) })); } setSaved(true); };
    const toggleConsent = async () => { if (apiClient) await apiClient.request("/api/v1/adaptation/consent", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ consent: !adaptation.consent }) }); setAdaptation((current) => ({ ...current, consent: !current.consent })); };
    const resetAdaptation = async () => { if (apiClient) await apiClient.request("/api/v1/adaptation/reset", { method: "POST" }); setAdaptation({ consent: false, suggestions: [] }); setSaved(true); };
    const adaptationFooter = <><Button onClick={() => decide("accept")} disabled={Boolean(apiClient) && (!proposal || !adaptation.consent)}>Прийняти зміну</Button><Button variant="secondary" onClick={() => decide("reject")} disabled={Boolean(apiClient) && (!proposal || !adaptation.consent)}>Залишити як є</Button><Button variant="tertiary" onClick={toggleConsent}>{adaptation.consent ? "Вимкнути збір даних" : "Дозволити Вектору вчитися"}</Button><Button variant="tertiary" onClick={resetAdaptation}>Скинути адаптацію</Button></>;
    return <AppFrame title="AI-адаптація" onBack={() => onNavigate("settings-home")} noNav footer={adaptationFooter} footerRows={4} contentAlign="center"><section className="adaptation"><span><Sparkle size={32} weight="duotone" /></span><h1>{proposal?.title ?? "Поки замало даних для адаптації"}</h1><p>{proposal?.detail ?? "Завершуй фокус-сесії у своєму темпі. Коли збереться достатньо даних, Вектор запропонує зміну — без автоматичних правок. Профіль не змінюється без твоєї згоди."}</p>{proposal ? <div className="adaptation-change"><span><small>Було</small><strong>Фокус-блок · 50 хв</strong></span><span><small>Рекомендація</small><strong>Фокус-блок · 60 хв</strong></span></div> : null}<InlineInsight>Ти можеш прийняти, відхилити або скинути цю рекомендацію у будь-який момент.</InlineInsight></section>{saved ? <UndoSnackbar message="Налаштування оновлено" onUndo={() => setSaved(false)} /> : null}</AppFrame>;
  }
  if (screenId === "settings-pro") return <AppFrame title="Lifetime Pro" onBack={() => onNavigate("settings-home")} noNav footer={<Button variant="secondary">Відновити покупку</Button>} contentAlign="center"><StateView state="success" title="Lifetime Pro активний" message="Необмежені цілі та всі майбутні Pro-функції доступні назавжди." /></AppFrame>;
  return <AppFrame title="Налаштування" onBack={() => onNavigate("today-normal")} noNav><section className="profile-card"><span>{DEMO_USER.initials}</span><div><h1>{DEMO_USER.name}</h1><p>olena@example.com</p></div></section><div className="settings-menu">{menu.map(([id,Icon,title,meta]) => <button key={id} onClick={() => onNavigate(id)}><span><Icon size={21} /></span><div><strong>{title}</strong><small>{meta}</small></div></button>)}</div><h2 className="settings-section-title">Інтеграції</h2><IntegrationRow type="telegram" onClick={() => onNavigate("settings-telegram")} /><IntegrationRow type="calendar" onClick={() => onNavigate("settings-calendar")} /></AppFrame>;
}
