const createScreens = (group, items) =>
  items.map(([id, title, kind = "default"]) => ({ id, group, title, kind }));

export const SCREEN_REGISTRY = [
  ...createScreens("Entry", [
    ["entry-chaos", "Chaos to Plan", "landing"],
    ["entry-voice", "Voice to Plan", "landing"],
    ["entry-path", "Path to Goal", "landing"],
    ["auth-loading", "Google authorization loading", "loading"],
    ["auth-error", "Помилка входу", "error"],
  ]),
  ...createScreens("Onboarding", [
    ["onboarding-welcome", "Welcome: три кроки"],
    ["calendar-permission", "Доступ до Google Calendar"],
    ["work-rhythm", "Робочі дні та години"],
    ["quiet-hours", "Тихі години та Telegram"],
    ["energy-peak", "Піковий час енергії"],
    ["focus-settings", "Фокус-блоки та денний ліміт"],
    ["goal-choice", "Вибір головної мети"],
    ["goal-manual", "Ручне введення мети"],
    ["goal-test-start", "Старт AI-тесту мети"],
    ["goal-test-result", "Результат AI-тесту"],
    ["goal-skip-warning", "Продовження без мети", "warning"],
    ["telegram-connect", "Підключення Telegram"],
    ["telegram-success", "Telegram підключено", "success"],
    ["first-brain-dump", "Перший Brain Dump"],
  ]),
  ...createScreens("Capture", [
    ["capture-chooser", "Голос або текст"],
    ["capture-recording", "Запис голосу", "recording"],
    ["capture-transcript", "Live transcript"],
    ["capture-processing", "AI опрацьовує думки", "loading"],
    ["capture-question-1", "Критичне уточнення 1"],
    ["capture-question-2", "Критичне уточнення 2"],
    ["capture-result", "AI Result", "success"],
    ["draft-plan-review", "Розбір збереженого Brain Dump"],
    ["capture-review", "Перевірити транскрипт", "warning"],
    ["capture-failure", "Brain Dump збережено в Inbox", "error"],
  ]),
  ...createScreens("Today", [
    ["today-empty", "Порожній день", "empty"],
    ["today-normal", "Запланований день"],
    ["today-active", "Активна Deep Work задача"],
    ["today-overload", "Перевантажений день", "warning"],
    ["today-rescheduled", "План автоматично перебудовано", "undo"],
    ["today-complete", "Усі задачі виконано", "success"],
    ["evening-review", "Вечірній підсумок"],
  ]),
  ...createScreens("Inbox", [
    ["inbox-default", "Inbox: задачі, ідеї, чернетки"],
    ["inbox-drafts", "Inbox: збережені чернетки"],
    ["inbox-ideas", "Inbox: збережені ідеї"],
    ["inbox-search", "Inbox search та filters"],
    ["inbox-failed-draft", "Необроблена чернетка", "error"],
    ["idea-detail", "Idea Detail"],
    ["idea-decomposition", "AI decomposition preview"],
    ["project-detail", "Project Detail"],
  ]),
  ...createScreens("Task", [
    ["task-detail", "Task Detail"],
    ["task-edit", "Task Edit"],
    ["task-subtasks", "Підзадачі"],
    ["pomodoro-setup", "Pomodoro setup"],
    ["focus-mode", "Focus Mode", "focus"],
    ["focus-complete", "Focus session completed", "success"],
  ]),
  ...createScreens("Calendar", [
    ["calendar-day", "Day Calendar"],
    ["calendar-week", "Week overview"],
    ["calendar-drag", "Переміщення задачі"],
    ["calendar-sheet", "Event / Task sheet"],
    ["calendar-conflict", "Calendar conflict", "warning"],
    ["calendar-offline", "Pending sync", "offline"],
  ]),
  ...createScreens("Oracle", [
    ["oracle-balanced", "Oracle Balanced"],
    ["oracle-goal-selected", "Goal selected"],
    ["oracle-idea-selected", "Idea selected"],
    ["oracle-path", "Show Path"],
    ["oracle-filters", "Oracle filters"],
    ["goal-focus-confirm", "Goal Focus confirmation"],
    ["goal-focus-active", "Goal Focus active", "focus"],
    ["oracle-suggested-edge", "AI suggested connection"],
    ["oracle-path-list", "Path list fallback"],
    ["oracle-empty", "Oracle без мети", "empty"],
  ]),
  ...createScreens("Goals", [
    ["goals-default", "Одна безкоштовна мета"],
    ["goal-add-second", "Додати другу мету"],
    ["paywall-lifetime", "Lifetime Pro $100", "paywall"],
    ["stripe-loading", "Stripe Checkout", "loading"],
    ["payment-success", "Lifetime Pro активний", "success"],
    ["payment-failed", "Платіж не завершено", "error"],
  ]),
  ...createScreens("Settings", [
    ["settings-home", "Профіль і налаштування"],
    ["settings-work", "Робочий ритм"],
    ["settings-energy", "Енергія та фокус"],
    ["settings-notifications", "Сповіщення і quiet hours"],
    ["settings-telegram", "Telegram integration"],
    ["settings-calendar", "Google Calendar integration"],
    ["settings-adaptation", "AI adaptation"],
    ["settings-pro", "Pro status і restore"],
  ]),
  ...createScreens("System", [
    ["system-offline", "Offline", "offline"],
    ["system-error", "Generic error", "error"],
    ["system-skeletons", "Loading skeletons", "loading"],
    ["system-undo", "Undo snackbar", "undo"],
    ["system-confirmation", "Незворотна ручна дія", "warning"],
  ]),
];

export const SCREEN_MAP = Object.fromEntries(
  SCREEN_REGISTRY.map((screen) => [screen.id, screen]),
);
